---
apiVersion: v1
kind: Service
metadata:
  name: backend-service2
  labels:
    app: backend-service2
spec:
  ports:
    - port: 1324
      protocol: TCP
      targetPort: 1324
  selector:
    app: back2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-deployment2
spec:
  selector:
    matchLabels:
      app: back2
  strategy:
    type: Recreate
  replicas: 2
  template:
    metadata:
      labels:
        app: back2
    spec:
      # volumes:
      # - name: databack
      #   emptyDir: {}
      containers:
      - name: backend2
        image:  lucina101/sds-final-backend2:latest
        env:
        - name: 'REDIS_HOST'
          value: 'db-service'
        ports:
        - containerPort: 1324
        # volumeMounts:
        # - mountPath: ./data/back
        #   name: databack
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 10
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 10
