---
    apiVersion: v1
    kind: Service
    metadata:
      name: backend-service3
      labels:
        app: backend-service3
    spec:
      ports:
        - port: 1323
          protocol: TCP
          targetPort: 1323
      selector:
        app: back3
    ---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: back-deployment
    spec:
      selector:
        matchLabels:
          app: back3
      replicas: 1
      template:
        metadata:
          labels:
            app: back3
        spec:
          volumes:
          - name: databack
            emptyDir: {}
          containers:
          - name: backend2
            image:  lucina101/sds-final-backend:latest
            env:
            - name: 'SERVER_NUMBER'
              value: '3'
            ports:
            - containerPort: 1323
            volumeMounts:
            - mountPath: ./data/back
              name: databack
    