---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend-service
spec:
  type: NodePort
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      nodePort: 30050
  selector:
    app: front
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
spec:
  selector:
    matchLabels:
      app: front
  replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: front
    spec:
      # volumes:
      # - name: datafront
      #   emptyDir: {}
      containers:
      - name: frontend
        image:  lucina101/sds-final-front:latest
        env:
        - name: 'SERVER_HOST'
          value: 'backend-service'
        - name: 'SERVER_PORT'
          value: '1323'
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        # volumeMounts:
        # - mountPath: /data/front
        #   name: datafront
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 10
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 10
