---
apiVersion: v1
kind: Service
metadata:
  name: backend-service3
  labels:
    app: backend-service3
spec:
  ports:
    - port: 1325
      protocol: TCP
      targetPort: 1325
  selector:
    app: back3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-deployment3
spec:
  selector:
    matchLabels:
      app: back3
  replicas: 1
  template:
    metadata:
      labels:
        app: back3
    spec:
      volumes:
      - name: databack
        emptyDir: {}
      containers:
      - name: backend3
        image:  lucina101/sds-final-backend3:latest
        env:
        - name: 'REDIS_HOST'
          value: 'db-service'
        ports:
        - containerPort: 1325
        volumeMounts:
        - mountPath: ./data/back
          name: databack