version: "3.8"

services:    
  todo:
    build: ../todo
    image: "todo:release-3"
    container_name: todo-service
    environment:
      REDIS_HOST: redis
      NOTIFICATION_HOST: notification
    networks:
      - todo-net
      
  webapp:
    build: ../todo-webapp
    image: "todo-webapp:release-3.1"
    container_name: webapp
    stdin_open: true
    ports:
      - 3000:3000
      
  notification:
    build: ../todo-notification
    image: "todo-notification:release-1.1"
    container_name: notification-service
    environment: 
      REDIS_HOST: redis
    networks:
      - todo-net
      
  redis:
    image: "redis"
    container_name: redis
    networks:
      - todo-net
    
  nginx:
    build: ../todo-nginx
    image: "todo-nginx:release-1"
    container_name: todo-nginx
    ports:
      - 8000:8000
    networks:
      - todo-net

networks:
    todo-net: {}



